#!/usr/bin/env python3
from __future__ import annotations
import json,re
from pathlib import Path
R=Path(__file__).resolve().parent
M=R/'source/bird_model.json'; C=R/'source/animation_clips.json'; J=R/'bird-animation.js'; T=R/'test_wing_model.py'; D=R/'README.md'
def at(c,t):
 for f in c['keyframes']:
  if abs(f['t']-t)<1e-9:return f
 raise KeyError(t)
m=json.loads(M.read_text()); assert m['version']=='1.2.0'; m['version']='1.3.0'; w=m['wing']; w['folded_pose']={'stroke_deg':176.0,'elbow_deg':34.0,'wrist_deg':42.0,'span_scale':0.72,'chord_scale':0.88}; w['shape_preservation'].update({'folded_span':0.72,'folded_articulation_weight':0.48,'extended_articulation_weight':0.04}); f=m['flight']; f.update({'outbound_bob_fade_start':0.78,'outbound_bob_fade_end':0.92,'outbound_rotation_fade_start':0.82,'outbound_rotation_fade_end':0.95,'outbound_exit_lift_px':3.5}); m['art_direction'].update({'resting_wing':'recognizable folded reference, not miniaturized','outbound_exit':'no downward bob during disappearance'}); M.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
l=json.loads(C.read_text()); assert l['version']=='1.2.0'; l['version']='1.3.0'; c=l['clips']; r=[176,34,42,.72,.88]; rm=[174,35,43,.72,.88]
for t,p in ((0,r),(.5,rm),(1,r)):at(c['perched_idle'],t)['wing']=p
at(c['anticipation_push'],0)['wing']=r; at(c['anticipation_push'],.3)['wing']=[184,29,34,.79,.91]
for t,p in ((.58,[194,20,23,.88,.94]),(.72,[181,26,31,.79,.90]),(1,[168,31,39,.72,.88])):at(c['touchdown'],t)['wing']=p
for t,p in {0:[168,31,39,.72,.88],.24:[172,33,41,.72,.88],.5:[175,34,42,.72,.88],.76:r,1:r}.items():at(c['settle'],t)['wing']=p
C.write_text(json.dumps(l,ensure_ascii=False,indent=2)+'\n')
s=J.read_text(); a='''          const bobWeight = smoothstep(0, 0.08, p);\n          const position = add(curve.position, [\n            sample.root[0] * bobWeight,\n            sample.root[1] * bobWeight,\n          ]);'''; b='''          const bobIn = smoothstep(0, 0.08, p);\n          const bobOut = 1 - smoothstep(\n            flight.outbound_bob_fade_start || 0.78,\n            flight.outbound_bob_fade_end || 0.92,\n            p\n          );\n          const bobWeight = bobIn * bobOut;\n          const exitLift = -(flight.outbound_exit_lift_px || 0) * smoothstep(\n            flight.outbound_bob_fade_start || 0.78, 1, p\n          );\n          const position = add(curve.position, [\n            sample.root[0] * bobWeight,\n            sample.root[1] * bobWeight + exitLift,\n          ]);'''; assert s.count(a)==1; s=s.replace(a,b)
a='''          const rotation = visualRotation(curve.tangent, false, -24, 7)\n            + sample.root[2] * 0.28;'''; b='''          const rotationWeight = 1 - smoothstep(\n            flight.outbound_rotation_fade_start || 0.82,\n            flight.outbound_rotation_fade_end || 0.95, p\n          );\n          const rotation = visualRotation(curve.tangent, false, -24, 7)\n            + sample.root[2] * 0.28 * rotationWeight;'''; assert s.count(a)==1; J.write_text(s.replace(a,b))
s=T.read_text().replace('assert model["version"] == "1.2.0"','assert model["version"] == "1.3.0"').replace('assert library["version"] == "1.2.0"','assert library["version"] == "1.3.0"'); a='assert wing["period_ms"] >= 2800, "the cruise wingbeat must stay deliberately slow"\n'; b='''assert wing["folded_pose"]["span_scale"] >= .70\nassert wing["folded_pose"]["chord_scale"] >= .85\nassert min(x["wing"][3] for x in library["clips"]["perched_idle"]["keyframes"]) >= .70\nassert flight["outbound_bob_fade_start"] < flight["outbound_bob_fade_end"] <= .94\nassert flight["outbound_exit_lift_px"] > 0\n'''; assert a in s; s=s.replace(a,a+b); a='assert "model.body.nodes.h5" in js\n'; b='''assert "outbound_bob_fade_start" in js\nassert "outbound_exit_lift_px" in js\nassert "rotationWeight" in js\n'''; assert a in s; T.write_text(s.replace(a,a+b))
s=D.read_text(); s=re.sub(r'^# Oiseau-réseau Percolia — direction \d+','# Oiseau-réseau Percolia — direction 07',s,count=1); sec='''\n## Sortie ascendante et ailes au repos\n\nLa chute juste avant la disparition venait du mouvement vertical additif de `cruise`, dont la sortie se terminait près de la pose la plus basse. Ce mouvement et la petite rotation additive s'annulent maintenant avant le bord ; un léger biais ascendant accompagne la disparition.\n\nLes ailes perchées restent pliées mais lisibles : 72 % de l'envergure et 88 % de la corde de référence.\n\n'''; i=s.find('\n## '); D.write_text(s[:i+1]+sec+s[i+1:])
Path(__file__).unlink(); print('applied v1.3')
