#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
P=ROOT/'Logo'/'Oiseau'/'bird-animation.js'
js=P.read_text(encoding='utf-8')

def between(text,start,end,repl):
    i=text.find(start); j=text.find(end,i)
    if i<0 or j<0: raise RuntimeError(f'marker missing: {start!r} / {end!r}')
    return text[:i]+repl+text[j:]

arc='''  function cubicDerivative(points, t) {\n    const [p0,p1,p2,p3]=points; const u=1-t;\n    return [3*u*u*(p1[0]-p0[0])+6*u*t*(p2[0]-p1[0])+3*t*t*(p3[0]-p2[0]),3*u*u*(p1[1]-p0[1])+6*u*t*(p2[1]-p1[1])+3*t*t*(p3[1]-p2[1])];\n  }\n\n  const arcTables=new WeakMap();\n  function arcTable(points) {\n    if (arcTables.has(points)) return arcTables.get(points);\n    const entries=[{t:0,length:0}]; let previous=cubic(points,0); let total=0;\n    for (let index=1; index<=160; index+=1) {\n      const t=index/160; const point=cubic(points,t); total+=length(sub(point,previous)); entries.push({t,length:total}); previous=point;\n    }\n    const table={entries,total}; arcTables.set(points,table); return table;\n  }\n  function cubicArcSample(points,fraction) {\n    const table=arcTable(points); const target=clamp(fraction,0,1)*table.total; let low=0; let high=table.entries.length-1;\n    while (high-low>1) { const middle=Math.floor((low+high)/2); if (table.entries[middle].length<target) low=middle; else high=middle; }\n    const a=table.entries[low], b=table.entries[high]; const alpha=b.length===a.length?0:(target-a.length)/(b.length-a.length); const t=lerp(a.t,b.t,alpha);\n    const before=cubic(points,Math.max(0,t-.006)); const after=cubic(points,Math.min(1,t+.006));\n    return {position:cubic(points,t),tangent:sub(after,before),parameter:t};\n  }\n  function speedProfile(progress,startSlope,endSlope) {\n    const t=clamp(progress,0,1); const a=startSlope+endSlope-2; const b=3-2*startSlope-endSlope;\n    return clamp(a*t*t*t+b*t*t+startSlope*t,0,1);\n  }\n  function hermitePoint(p0,p1,m0,m1,t) {\n    const u=clamp(t,0,1),u2=u*u,u3=u2*u; const h00=2*u3-3*u2+1,h10=u3-2*u2+u,h01=-2*u3+3*u2,h11=u3-u2;\n    return [h00*p0[0]+h10*m0[0]+h01*p1[0]+h11*m1[0],h00*p0[1]+h10*m0[1]+h01*p1[1]+h11*m1[1]];\n  }\n\n'''
js=between(js,'  function cubicDerivative(points, t) {\n','  function readModel(svg) {\n',arc)

sampling='''  function hermiteWithTangents(p1,p2,m1,m2,t1,t2,t) {\n    const duration=Math.max(1e-9,t2-t1),u=clamp((t-t1)/duration,0,1),u2=u*u,u3=u2*u;\n    return (2*u3-3*u2+1)*p1+(u3-2*u2+u)*duration*m1+(-2*u3+3*u2)*p2+(u3-u2)*duration*m2;\n  }\n  function pchipTangent(h0,h1,d0,d1) {\n    if (h0<=0||h1<=0||d0*d1<=0) return 0; const w1=2*h1+h0,w2=h1+2*h0; return (w1+w2)/(w1/d0+w2/d1);\n  }\n  function sampleTrack(frames,key,progress,loop=false) {\n    if (frames.length===1) return frames[0][key].slice();\n    const source=loop&&frames.length>2&&Math.abs(frames[frames.length-1].t-1)<1e-9?frames.slice(0,-1):frames;\n    let t=loop?((progress%1)+1)%1:clamp(progress,0,1),f0,f1,f2,f3,t0,t1,t2,t3;\n    if (loop) {\n      const n=source.length; let index=n-1;\n      for (let i=0;i<n;i+=1) { const next=(i+1)%n,end=source[next].t+(next<=i?1:0),candidate=t<source[i].t?t+1:t; if (candidate<=end) {index=i;t=candidate;break;} }\n      const next=(index+1)%n,prev=(index-1+n)%n,after=(next+1)%n; f0=source[prev];f1=source[index];f2=source[next];f3=source[after];\n      t1=f1.t;t2=f2.t;while(t2<=t1)t2+=1;t0=f0.t;while(t0>=t1)t0-=1;t3=f3.t;while(t3<=t2)t3+=1;\n    } else {\n      if (t<=source[0].t) return source[0][key].slice(); if (t>=source[source.length-1].t) return source[source.length-1][key].slice();\n      let index=source.length-2; for(let i=0;i<source.length-1;i+=1){if(t<=source[i+1].t){index=i;break;}}\n      f1=source[index];f2=source[index+1];f0=source[Math.max(0,index-1)];f3=source[Math.min(source.length-1,index+2)];\n      t1=f1.t;t2=f2.t;t0=index>0?f0.t:t1-(t2-t1);t3=index+2<source.length?f3.t:t2+(t2-t1);\n    }\n    const output=[];\n    for(let component=0;component<f1[key].length;component+=1){\n      const p0=f0[key][component],p1=f1[key][component],p2=f2[key][component],p3=f3[key][component];\n      const h0=t1-t0,h1=t2-t1,h2=t3-t2,d0=(p1-p0)/Math.max(1e-9,h0),d1=(p2-p1)/Math.max(1e-9,h1),d2=(p3-p2)/Math.max(1e-9,h2);\n      output.push(hermiteWithTangents(p1,p2,pchipTangent(h0,h1,d0,d1),pchipTangent(h1,h2,d1,d2),t1,t2,t));\n    }\n    return output;\n  }\n\n'''
js=between(js,'  function hermiteValue(','  function sampleClip(library, name, progress) {\n',sampling)
js=js.replace("sampleTrack(clip.keyframes, 'root', t)","sampleTrack(clip.keyframes, 'root', t, clip.loop)")
js=js.replace("sampleTrack(clip.keyframes, 'wing', t)","sampleTrack(clip.keyframes, 'wing', t, clip.loop)")
js=js.replace("sampleTrack(clip.keyframes, 'legs', t)","sampleTrack(clip.keyframes, 'legs', t, clip.loop)")
blend='''\n  function blendRigSample(previous,current,amount) {\n    const t=clamp(amount,0,1);\n    return {root:[current.root[0],current.root[1],lerp(previous.root[2],current.root[2],t),lerp(previous.root[3],current.root[3],t)],wing:current.wing.map((v,i)=>lerp(previous.wing[i],v,t)),legs:current.legs.map((v,i)=>lerp(previous.legs[i],v,t))};\n  }\n'''
js=js.replace('  function eventTime(library, clipName, eventName) {\n',blend+'\n  function eventTime(library, clipName, eventName) {\n')
old="      const sample = entry.clip ? sampleClip(library, entry.clip, cp) : null;\n"
new="      let sample = entry.clip ? sampleClip(library, entry.clip, cp) : null;\n      if (sample && entry.blend_in_ms) {\n        const index=boundaries.indexOf(entry), previous=index>0?boundaries[index-1]:null, fraction=Math.min(1,entry.blend_in_ms/entry.duration_ms);\n        if (previous&&previous.clip&&p<fraction) sample=blendRigSample(sampleClip(library,previous.clip,clipProgress(previous,previous.end-.001)),sample,smoothstep(0,fraction,p));\n      }\n"
if old not in js: raise RuntimeError('sample marker missing')
js=js.replace(old,new)

push='''        case 'push_off': {\n          outbound.setWingPose(sample.wing); let legState=outbound.setLegPose(sample.legs);\n          const scale=flight.perched_scale*sample.root[3],rotation=sample.root[2],toe=eventTime(library,'push_off','toe_off'); let position;\n          if (p<=toe) position=outbound.contactPosition(perch,scale,false,rotation,legState.contactLocal);\n          else {\n            const release=pushReleasePose(), beforeProgress=Math.max(0,toe-.025), beforeSample=sampleClip(library,'push_off',beforeProgress);\n            const beforeLeg=outbound.setLegPose(beforeSample.legs);\n            const beforePosition=outbound.contactPosition(perch,flight.perched_scale*beforeSample.root[3],false,beforeSample.root[2],beforeLeg.contactLocal);\n            outbound.setWingPose(sample.wing); legState=outbound.setLegPose(sample.legs);\n            const end=pushEndPose(),u=(p-toe)/(1-toe),contactDerivative=mul(sub(release.position,beforePosition),(1-toe)/Math.max(1e-6,toe-beforeProgress));\n            const nextEntry=boundaries.find((item)=>item.state==='takeoff'),startPose=sampleClip(library,'takeoff',0),nextPose=sampleClip(library,'takeoff',.025);\n            const takeoffDerivative=mul(sub(nextPose.root.slice(0,2),startPose.root.slice(0,2)),((1-toe)*entry.duration_ms)/(.025*nextEntry.duration_ms));\n            position=hermitePoint(release.position,end.position,contactDerivative,takeoffDerivative,u);\n          }\n          outbound.place(position,[1,-.25],scale,false,1,rotation); break;\n        }\n\n'''
js=between(js,"        case 'push_off': {\n","        case 'takeoff': {\n",push)
takeoff='''        case 'takeoff': {\n          const origin=pushEndPose(),first=library.clips.takeoff.keyframes[0].root;\n          let position=add(origin.position,[sample.root[0]-first[0],sample.root[1]-first[1]]);\n          const target=library.world.outbound_curve[0],endSample=sampleClip(library,'takeoff',1),authoredEnd=add(origin.position,[endSample.root[0]-first[0],endSample.root[1]-first[1]]);\n          position=add(position,mul(sub(target,authoredEnd),smoothstep(.62,1,p))); outbound.setWingPose(sample.wing); outbound.setLegPose(sample.legs);\n          const initialRoot=sampleClip(library,'takeoff',0).root,initialBase=origin.scale/Math.max(1e-6,initialRoot[3]),baseScale=lerp(initialBase,flight.bird_scale,smoothstep(0,.62,p));\n          outbound.place(position,[1,-.35],baseScale*sample.root[3],false,1,sample.root[2]); break;\n        }\n\n'''
js=between(js,"        case 'takeoff': {\n","        case 'outbound': {\n",takeoff)
outbound='''        case 'outbound': {\n          const curve=cubicArcSample(library.world.outbound_curve,speedProfile(p,.58,1.02)),bobWeight=smoothstep(0,.08,p);\n          const position=add(curve.position,[sample.root[0]*bobWeight,sample.root[1]*bobWeight]); outbound.setWingPose(sample.wing); outbound.setLegPose(sample.legs);\n          const fade=1-smoothstep(.93,1,p),rotation=visualRotation(curve.tangent,false,-24,7)+sample.root[2]*.28;\n          outbound.place(position,curve.tangent,flight.bird_scale*sample.root[3],false,fade,rotation);\n          const scanHalf=library.world.scan_duration_fraction/2,scanDistance=Math.abs(p-library.world.scan_progress),scanStrength=1-clamp(scanDistance/scanHalf,0,1),scanSweep=clamp((p-(library.world.scan_progress-scanHalf))/(2*scanHalf),0,1);\n          outbound.setLidar(scanStrength,scanSweep); break;\n        }\n\n'''
js=between(js,"        case 'outbound': {\n","        case 'empty':\n",outbound)
inbound='''        case 'inbound': {\n          const curve=cubicArcSample(library.world.inbound_curve,speedProfile(p,1.02,.42)),bobWeight=smoothstep(0,.08,p)*(1-smoothstep(.86,1,p));\n          const position=add(curve.position,[-sample.root[0]*bobWeight,sample.root[1]*bobWeight]); inbound.setWingPose(sample.wing); inbound.setLegPose(sample.legs);\n          const rotation=visualRotation(curve.tangent,true,-14,5)-sample.root[2]*.22;\n          inbound.place(position,curve.tangent,flight.bird_scale*sample.root[3],true,smoothstep(0,.08,p),rotation); break;\n        }\n\n'''
js=between(js,"        case 'inbound': {\n","        case 'approach':\n",inbound)
P.write_text(js,encoding='utf-8')
Path(__file__).unlink(); print('motion smoothing and takeoff impulse installed')
