"""Rebuild the introductory HDBSCAN example as vector TikZ (same data/settings)."""
from pathlib import Path
import json
import numpy as np
import sklearn
from sklearn.cluster import HDBSCAN

HERE = Path(__file__).resolve().parent

def main() -> None:
    data = np.load(HERE/'assets/clusterable_data.npy',allow_pickle=False)
    if data.shape != (2309,2) or not np.isfinite(data).all():
        raise ValueError('Unexpected 2D reference data')
    labels = HDBSCAN(min_cluster_size=15,min_samples=16,
                     cluster_selection_method='eom',copy=True).fit_predict(data)
    colors = {-1:'gray!45',0:'inriablue',1:'inriamauve',
              2:'inriagreen!80!black',3:'inriared!85!black',
              4:'inrialightblue!80!black',5:'inriaorange'}
    if set(labels)-set(colors):
        raise ValueError('Unexpected cluster labels; review the colour mapping.')
    xy = (data-data.min(axis=0))/(data.max(axis=0)-data.min(axis=0))
    xy = xy*np.array([4.2,2.75])+np.array([.1,.1])
    lines = [r'% Generated by make_figures.py; original HDBSCAN example.',
             r'\begin{tikzpicture}[every node/.style={font=\fontsize{9}{11}\selectfont},line cap=round]',
             r'\useasboundingbox (0,-0.15) rectangle (10.3,3.5);']
    for offset,label,raw in [(0.,'Unlabelled points',True),(5.9,'HDBSCAN [3]',False)]:
        lines += [rf'\begin{{scope}}[xshift={offset}cm]',
                  r'\fill[white] (0,0) rectangle (4.4,3.0);',
                  r'\draw[inriagrayblue!20,line width=.4pt] (0,0) rectangle (4.4,3.0);',
                  rf'\node[font=\fontsize{{10}}{{12}}\selectfont\bfseries,text=inriagrayblue] at (2.2,3.27) {{{label}}};']
        for group in sorted(colors):
            color = 'inriablue!85!black' if raw else colors[group]
            coords = ','.join(f'{x:.5f}/{y:.5f}' for x,y in xy[labels==group])
            lines += [rf'\foreach \x/\y in {{{coords}}}',
                      rf'{{\fill[{color},opacity=.78] (\x,\y) circle[radius=.0095];}}']
        lines.append(r'\end{scope}')
    lines += [r'\draw[-{Latex[length=4mm]},line width=1.4pt,inriagrayblue!65] (4.65,1.55)--(5.63,1.55);',
              r'\end{tikzpicture}']
    (HERE/'figures/clustering.tex').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    summary = {'dataset':'HDBSCAN clusterable_data.npy','n_points':len(data),
               'scikit_learn':sklearn.__version__,'min_cluster_size':15,'min_samples':16,
               'cluster_counts':{str(int(k)):int(v) for k,v in zip(*np.unique(labels,return_counts=True))},
               'purpose':'Introductory example only; not an HGP-versus-HDBSCAN benchmark.'}
    (HERE/'assets/clustering_metadata.json').write_text(json.dumps(summary,indent=2)+'\n')

if __name__ == '__main__':
    main()
